# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c451b7e269e322fac2d0fda488a8d8238ef51ca247fc71bb1c81578e44f105dbd5bf1431a87a7fa0cbf5cd7f9317d58d8c843073b7929796d10e5c897c32c31f

test:
  secret_key_base: f8b14cd5a5d095278710e897b635078e3d52a7330f9c94d97b1e2fa6a0764843800df66116ef48dcf5d35685d1be0b5f11b8b91572cb2af04baabb6db7a87a94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
